### ISSUE TITLE
The updated Jar on Maven repo is empty

### ISSUE THREAD

**Issue by huzaifarasheedmir** [wireapp/cryptobox-jni#14]
Hi,

I was having build errors mentioning
```
object cryptobox is not a member of package com.wire
```

Although it was working before. After some research, I found there has been a recent update on the Maven repo on 14 April 
I downloaded the jar and tried to see its content. It doesn't have any cryptobox classes/packages it just has 
ETA-INF/MANIFEST.MF file in it.

Kindly double check if it can be resolved
https://mvnrepository.com/artifact/com.wire/cryptobox-android/1.1.2

<img width="1359" alt="Screenshot 2021-04-25 at 2 41 39 AM" src="https://user-images.githubusercontent.com/12775679/115973616-e06b1880-a56f-11eb-8927-f62ee696c4d4.png">

**Comment by vitorhugods** [comment]
Hello,

It was indeed a flawed `.jar` artifact. This was our first release to Maven Central and unfortunately it didn't go as planned.

The intention was to have a working `.aar`, and this was achieved today with [version `1.1.3`](https://search.maven.org/artifact/com.wire/cryptobox-android/1.1.3/aar).

You can give it a go now.
